def testaPin_analog_3(_pin: number):
    for index in range(4):
        pins.analog_write_pin(AnalogPin.P3, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P3, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P3, 1023)
    pins.analog_write_pin(AnalogPin.P3, 0)
def testDigPin_15():
    pins.digital_write_pin(DigitalPin.P15, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P15, 0)
    basic.pause(100)
def testaPin_analog_1(_pin2: number):
    for index2 in range(4):
        pins.analog_write_pin(AnalogPin.P1, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P1, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P1, 1023)
    pins.analog_write_pin(AnalogPin.P1, 0)
def testaPin_analog_4(_pin3: number):
    for index3 in range(4):
        pins.analog_write_pin(AnalogPin.P4, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P4, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P4, 1023)
    pins.analog_write_pin(AnalogPin.P4, 0)
def testaPin_analog_0(_pin4: number):
    for index4 in range(4):
        pins.analog_write_pin(AnalogPin.P0, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P0, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P0, 1023)
    pins.analog_write_pin(AnalogPin.P0, 0)
def testDigPin_14():
    pins.digital_write_pin(DigitalPin.P14, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P14, 0)
    basic.pause(100)
def testDigPin_7():
    pins.digital_write_pin(DigitalPin.P7, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P7, 0)
    basic.pause(100)
def testDigPin_12():
    pins.digital_write_pin(DigitalPin.P12, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P12, 0)
    basic.pause(100)
def testDigPin_6():
    pins.digital_write_pin(DigitalPin.P6, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P6, 0)
    basic.pause(100)
def testDigPin_13():
    pins.digital_write_pin(DigitalPin.P13, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P13, 0)
    basic.pause(100)
def testDigPin_9():
    pins.digital_write_pin(DigitalPin.P9, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P9, 0)
    basic.pause(100)
def testDigPin_8():
    pins.digital_write_pin(DigitalPin.P8, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P8, 0)
    basic.pause(100)
def testaPin_analog_2(_pin5: number):
    for index5 in range(4):
        pins.analog_write_pin(AnalogPin.P2, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P2, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P2, 1023)
    pins.analog_write_pin(AnalogPin.P2, 0)
def testDigPin_16():
    pins.digital_write_pin(DigitalPin.P16, 1)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P16, 0)
    basic.pause(100)
def testaPin_analog_10(_pin6: number):
    for index6 in range(4):
        pins.analog_write_pin(AnalogPin.P10, 100)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P10, 500)
        basic.pause(100)
        pins.analog_write_pin(AnalogPin.P10, 1023)
    pins.analog_write_pin(AnalogPin.P10, 0)
led.enable(False)
pins.analog_write_pin(AnalogPin.P0, 0)
pins.analog_write_pin(AnalogPin.P1, 0)
pins.analog_write_pin(AnalogPin.P2, 0)
pins.analog_write_pin(AnalogPin.P3, 0)
pins.analog_write_pin(AnalogPin.P4, 0)
pins.analog_write_pin(AnalogPin.P10, 0)
pins.digital_write_pin(DigitalPin.P5, 0)
pins.digital_write_pin(DigitalPin.P6, 0)
pins.digital_write_pin(DigitalPin.P6, 0)
pins.digital_write_pin(DigitalPin.P7, 0)
pins.digital_write_pin(DigitalPin.P8, 0)
pins.digital_write_pin(DigitalPin.P9, 0)
pins.digital_write_pin(DigitalPin.P11, 0)
pins.digital_write_pin(DigitalPin.P12, 0)
pins.digital_write_pin(DigitalPin.P13, 0)
pins.digital_write_pin(DigitalPin.P14, 0)
pins.digital_write_pin(DigitalPin.P15, 0)
pins.digital_write_pin(DigitalPin.P16, 0)
testaPin_analog_0(0)
testaPin_analog_1(1)
testaPin_analog_2(1)
testaPin_analog_3(1)
testaPin_analog_4(1)
testaPin_analog_10(1)
basic.pause(1000)
testDigPin_6()
testDigPin_7()
testDigPin_8()
testDigPin_9()
testDigPin_12()
testDigPin_13()
testDigPin_14()
testDigPin_15()
testDigPin_16()
pins.digital_write_pin(DigitalPin.P5, 1)
pins.digital_write_pin(DigitalPin.P11, 1)

def on_forever():
    pass
basic.forever(on_forever)
